name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: ['8.2', '8.3', '8.4', '8.5']
    name: Test with PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Check PHP Version
      run: php -v

    - name: Validate composer.json
      run: composer validate

    - name: Resolve dependencies for this PHP version
      run: composer update --prefer-dist --no-progress --no-interaction

    - name: Run test suite
      run: composer run-script test

